name: Benchmarks

on:
  workflow_dispatch:
    inputs:
      benchtime:
        description: "Iterations (-benchtime)"
        default: "1s"
        required: true
      timeout:
        description: "Timeout (-timeout)"
        default: "0"
        required: true
      regex:
        description: "Pattern"
        default: "."
        required: true

jobs:
  bench:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pkg: [ds, algo]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18.1'
        check-latest: true

    - name: Benchmark
      run: go test -benchmem -memprofile mem.out -cpuprofile cpu.out -benchtime ${{ inputs.benchtime }} -timeout ${{ inputs.timeout }} -bench ${{ inputs.pattern }} ./${{ matrix.pkg }}

    - name: Upload Memory Profile
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pkg }}-mem-profile
        path: mem.out

    - name: Upload CPU Profile
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pkg }}-cpu-profile
        path: cpu.out
