name: Benchmarks

on: workflow_dispatch

jobs:
  bench:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pkg: [ds, algo]

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18.1'
        check-latest: true

    - name: Benchmark
      run: make bench PKG=${{ matrix.pkg }}

    - name: Upload Memory Profile
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pkg }}-mem-profile
        path: mem.out

    - name: Upload CPU Profile
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pkg }}-cpu-profile
        path: cpu.out
