name: Benchmarks

on: workflow_dispatch

jobs:
  bench:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18.1'
        check-latest: true

    - name: Benchmark
      run: make bench
