name: CI

on: push

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18.1'
        check-latest: true

    - name: Test
      run: make test

    - name: Coverage Conversion
      uses: jandelgado/gcov2lcov-action@v1
      with:
        infile: coverage.out
        outfile: coverage.lcov

    - name: Coverage Upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
